apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::160885291806:role/ec2-administator-role
      username: ec2-admin
      groups:
        - system:masters
